### ISSUE TITLE
UI v2

### ISSUE THREAD

**Issue by 957SWARM** [957SWARM/957-Bunny-Bots-23#55]
## Background

Our drivers need a better UI for troubleshooting and ensuring the robot functions properly on the field. The software team could also use a good UI for testing in the pits and at the shop.

To accomplish this, we will extend the functionality of our beta UI for Bunny Bots to display more information.

## Tasks

- [x] Add a readout for the gyro angle.
- [x] Add a readout for the shooter setpoint.
- [x] Add a readout for the intake state (may need to modify enum to add a string).
- [x] Add a readout for the robot state (may need to modify enum to add a string).
- [x] Show if transfer wheel is enabled.
- [x] Add a readout for the state of the break beam sensor (just use the getter function from the subsystem)
- [x] Determine the extent of additional features to add.

## Acceptance Criteria

- [x] All fields update properly when changes to internal robot state occur.
- [x] Additional features chosen by team update properly and are fully implemented.

**Comment by thePand251** [comment]
Due to time constraints, UI v2 is now feature-complete.
